In [1]:
import torch

In [2]:
x_train = torch.FloatTensor([[1,2,1,1],[2,1,3,2],[3,1,3,4],[4,1,5,5],[1,7,5,5],[1,2,5,6],[1,6,6,6],[1,7,7,7]])
y_train = torch.FloatTensor([[0,0,1],[0,0,1],[0,0,1],[0,1,0],[0,1,0],[0,1,0],[1,0,0],[1,0,0]])

In [3]:
x_train.shape, y_train.shape

(torch.Size([8, 4]), torch.Size([8, 3]))

In [12]:
W = torch.zeros(4,3,requires_grad = True)
b = torch.zeros(1,3,requires_grad = True)

optimizer = torch.optim.Adam([W,b],lr=0.1)

for epoch in range(3001):
    hypotesis = torch.softmax(torch.mm(x_train,W)+b, dim=1)
    cost = -torch.mean(torch.sum(y_train*torch.log(hypotesis),dim=1))
    
    optimizer.zero_grad()
    cost.backward()
    optimizer.step()
    
    if epoch % 300 == 0:
        print("epoch: {}, cost: {:.6f}".format(epoch,cost.item()))

epoch: 0, cost: 1.098612
epoch: 300, cost: 0.105262
epoch: 600, cost: 0.042634
epoch: 900, cost: 0.023111
epoch: 1200, cost: 0.014479
epoch: 1500, cost: 0.009879
epoch: 1800, cost: 0.007124
epoch: 2100, cost: 0.005338
epoch: 2400, cost: 0.004113
epoch: 2700, cost: 0.003236
epoch: 3000, cost: 0.002588


In [5]:
W.requires_grad_(False)
b.requires_grad_(False)

x_test = torch.FloatTensor([[1,11,10,9],[1,3,4,3],[1,1,0,1]])
test_all = torch.softmax(torch.mm(x_test,W)+b,dim=1)
print(test_all)
print(torch.argmax(test_all,dim=1))

tensor([[1.0000e+00, 5.5163e-19, 7.0148e-38],
        [1.4800e-02, 7.4294e-01, 2.4226e-01],
        [1.2256e-33, 9.0835e-12, 1.0000e+00]])
tensor([0, 1, 2])


# 좀더 깔끔하게 softmax

In [6]:
import torch.nn.functional as F

In [7]:
new_y_train = torch.LongTensor([2,2,2,1,1,1,0,0])

In [8]:
z = torch.mm(x_train,W) + b
cost = F.cross_entropy(z,new_y_train)

## 최종 코드

In [13]:
import torch.nn as nn

model = nn.Linear(4,3)
optimizer = torch.optim.Adam(model.parameters(),lr=0.1)

for epoch in range(3001):
    z = model(x_train)
    cost = F.cross_entropy(z,new_y_train)
    
    optimizer.zero_grad()
    cost.backward()
    optimizer.step()
    
    if epoch % 300 == 0:
        print("epoch: {}, cost: {:.6f}".format(epoch,cost.item()))

epoch: 0, cost: 1.604301
epoch: 300, cost: 0.095328
epoch: 600, cost: 0.038717
epoch: 900, cost: 0.021047
epoch: 1200, cost: 0.013211
epoch: 1500, cost: 0.009024
epoch: 1800, cost: 0.006513
epoch: 2100, cost: 0.004883
epoch: 2400, cost: 0.003764
epoch: 2700, cost: 0.002963
epoch: 3000, cost: 0.002370


In [36]:
x_test = torch.FloatTensor([[1,11,10,9],[1,3,4,3],[1,1,0,1]])
test_all = model(x_test)
print(torch.softmax(test_all,dim=1))
print(torch.argmax(test_all,dim=1))

tensor([[1.0000e+00, 2.9982e-17, 4.3590e-35],
        [9.4510e-04, 8.1855e-01, 1.8051e-01],
        [5.8326e-31, 5.5921e-11, 1.0000e+00]], grad_fn=<SoftmaxBackward>)
tensor([0, 1, 2])
