In [1]:
import torch

In [2]:
x = torch.tensor([[1,2,3],[4,5,6],[7,8,9]])
y = torch.FloatTensor([[1,2,3],[4,5,6],[7,8,9]])
print("x = ",x)
print("y = ",y)

x =  tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])
y =  tensor([[1., 2., 3.],
        [4., 5., 6.],
        [7., 8., 9.]])


In [3]:
x.shape, x.size(), x.ndimension()

(torch.Size([3, 3]), torch.Size([3, 3]), 2)

In [4]:
x0 = torch.unsqueeze(x,0)
x1 = torch.unsqueeze(x,1)
x2 = torch.unsqueeze(x,2)
x0.shape, x1.shape, x2.shape

(torch.Size([1, 3, 3]), torch.Size([3, 1, 3]), torch.Size([3, 3, 1]))

In [5]:
x0

tensor([[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]])

In [6]:
x1

tensor([[[1, 2, 3]],

        [[4, 5, 6]],

        [[7, 8, 9]]])

In [7]:
x2

tensor([[[1],
         [2],
         [3]],

        [[4],
         [5],
         [6]],

        [[7],
         [8],
         [9]]])

In [8]:
x.view(9)

tensor([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [9]:
x.view(1,3,3)

tensor([[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]])

In [2]:
x = torch.FloatTensor([[1,2],[3,4],[5,6]])
w = torch.randn(1,2,dtype=torch.float)
b = torch.randn(3,1, dtype=torch.float)

result = torch.mm(x,torch.t(w)) + b
result

tensor([[1.1333],
        [1.2457],
        [2.1497]])

In [7]:
x_train = torch.FloatTensor([[1,2],[3,2],[3,7],[1,1],[1,0]])
y_train = torch.FloatTensor([[4],[8],[23],[1],[-2]])

w = torch.zeros(2,1)
b = torch.zeros(1,1)

lr = 0.01

for epoch in range(3001):
    w.requires_grad_(True)
    b.requires_grad_(True)
    
    hypothesis = torch.mm(x_train,w) + b
    cost = torch.mean((hypothesis - y_train)**2)
    
    cost.backward()
    with torch.no_grad():
        w = w - lr*w.grad
        b = b - lr*b.grad
    if epoch % 100 == 0:
        print("epoch : {}, cost : {}, W : {}, b : {}".format(epoch,cost,w,b))

epoch : 0, cost : 122.80000305175781, W : tensor([[0.3840],
        [0.7440]]), b : tensor([[0.1360]])
epoch : 100, cost : 1.5337575674057007, W : tensor([[0.6226],
        [3.1603]]), b : tensor([[-1.3651]])
epoch : 200, cost : 0.7582406401634216, W : tensor([[0.9143],
        [3.1864]]), b : tensor([[-2.1790]])
epoch : 300, cost : 0.38928863406181335, W : tensor([[1.2106],
        [3.1417]]), b : tensor([[-2.7023]])
epoch : 400, cost : 0.20005789399147034, W : tensor([[1.4328],
        [3.1025]]), b : tensor([[-3.0705]])
epoch : 500, cost : 0.10281282663345337, W : tensor([[1.5932],
        [3.0736]]), b : tensor([[-3.3338]])
epoch : 600, cost : 0.05283749848604202, W : tensor([[1.7084],
        [3.0528]]), b : tensor([[-3.5224]])
epoch : 700, cost : 0.027154315263032913, W : tensor([[1.7909],
        [3.0378]]), b : tensor([[-3.6576]])
epoch : 800, cost : 0.013955106027424335, W : tensor([[1.8501],
        [3.0271]]), b : tensor([[-3.7546]])
epoch : 900, cost : 0.007171782664954662,