In [2]:
import pandas as pd
from pandas import Series, DataFrame
import numpy as np
import matplotlib.pyplot as plt
%matplotlib inline 
# 그린 그림 주피터 안에서 보겠다는 의미. 

UsageError: unrecognized arguments: # 그린 그림 주피터 안에서 보겠다는 의미.


In [3]:
plt.rc('font', family='Malgun Gothic') # 한글의 폰트를 맑은고딕 사용
plt.rc('axes', unicode_minus=False) # - 기호를 사용할때 한글 폰트를 불러오면 -기호가 깨지기 때문에 실행해 주어야 한다. 

In [4]:
data = {'state': ['Ohio', 'Ohio', 'Ohio', 'Nevada', 'Nevada'],
        'year': [2000, 2001, 2002, 2001, 2002],
        'pop': [1.5, 1.7, 3.6, 2.4, 2.9]}
df = DataFrame(data)
df

state  year  pop
0    Ohio  2000  1.5
1    Ohio  2001  1.7
2    Ohio  2002  3.6
3  Nevada  2001  2.4
4  Nevada  2002  2.9

In [62]:
df.index,df.index.values,df.columns,df.values,df.shape

(RangeIndex(start=0, stop=5, step=1),
 array([0, 1, 2, 3, 4], dtype=int64),
 Index(['state', 'year', 'pop'], dtype='object'),
 array([['Ohio', 2000, 1.5],
        ['Ohio', 2001, 1.7],
        ['Ohio', 2002, 3.6],
        ['Nevada', 2001, 2.4],
        ['Nevada', 2002, 2.9]], dtype=object),
 (5, 3))

In [68]:
len(df),df.size,df.dtypes

(5, 15, state     object
 year       int64
 pop      float64
 dtype: object)

In [69]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 3 columns):
state    5 non-null object
year     5 non-null int64
pop      5 non-null float64
dtypes: float64(1), int64(1), object(1)
memory usage: 200.0+ bytes


In [65]:
df.describe(percentiles=[.1,.2,.3,.4,.5,.6,.7,.8,.9])

year       pop
count     5.00000  5.000000
mean   2001.20000  2.420000
std       0.83666  0.864292
min    2000.00000  1.500000
10%    2000.40000  1.580000
20%    2000.80000  1.660000
30%    2001.00000  1.840000
40%    2001.00000  2.120000
50%    2001.00000  2.400000
60%    2001.40000  2.600000
70%    2001.80000  2.800000
80%    2002.00000  3.040000
90%    2002.00000  3.320000
max    2002.00000  3.600000

In [70]:
df.get_dtype_counts()

float64    1
int64      1
object     1
dtype: int64

In [71]:
df.describe().astype('int')

year  pop
count     5    5
mean   2001    2
std       0    0
min    2000    1
25%    2001    1
50%    2001    2
75%    2002    2
max    2002    3

In [72]:
df.describe().astype('float')

year       pop
count     5.00000  5.000000
mean   2001.20000  2.420000
std       0.83666  0.864292
min    2000.00000  1.500000
25%    2001.00000  1.700000
50%    2001.00000  2.400000
75%    2002.00000  2.900000
max    2002.00000  3.600000

In [76]:
display(df.state.value_counts())
display(df.state.unique())

Ohio      3
Nevada    2
Name: state, dtype: int64

array(['Ohio', 'Nevada'], dtype=object)

In [79]:
df['pop'].gt(2) # lt, gt, le, ge, eq, ne

0    False
1    False
2     True
3     True
4     True
Name: pop, dtype: bool

In [82]:
df['pop'].add(1).mul(2).floordiv(3) # .찍고 .찍고 계속 이어가는것 method chaining이라 한다. 

0    1.0
1    1.0
2    3.0
3    2.0
4    2.0
Name: pop, dtype: float64

In [83]:
df['pop'].dtypes == 'float64', df['pop'].dtypes == 'float', df['pop'].dtypes == 'float32'

(True, True, False)

In [84]:
df['pop'].dtypes == np.float64, df['pop'].dtypes == np.float, df['pop'].dtypes == np.float16
# 데이터 타입 np. 을 쓰던 그냥 쓰던 같다. 

(True, True, False)

In [85]:
x = df
df['year'] = df['year'] + 1 
x # df에 있는 year의 값을 수정했지만 x에서도 바뀜.. 

state  year  pop
0    Ohio  2001  1.5
1    Ohio  2002  1.7
2    Ohio  2003  3.6
3  Nevada  2002  2.4
4  Nevada  2003  2.9

In [87]:
x = df.copy()
df['year'] = df['year'] + 1 
display(x)
display(df)

state  year  pop
0    Ohio  2002  1.5
1    Ohio  2003  1.7
2    Ohio  2004  3.6
3  Nevada  2003  2.4
4  Nevada  2004  2.9

state  year  pop
0    Ohio  2003  1.5
1    Ohio  2004  1.7
2    Ohio  2005  3.6
3  Nevada  2004  2.4
4  Nevada  2005  2.9

In [95]:
display(df.min()),display(df.min(axis=0)),display(df.min(axis=1)),display(df.sum(axis=0)),display(df.sum(axis=1))

state    Nevada
year       2003
pop         1.5
dtype: object

state    Nevada
year       2003
pop         1.5
dtype: object

0    1.5
1    1.7
2    3.6
3    2.4
4    2.9
dtype: float64

state    OhioOhioOhioNevadaNevada
year                        10021
pop                          12.1
dtype: object

0    2004.5
1    2005.7
2    2008.6
3    2006.4
4    2007.9
dtype: float64

(None, None, None, None, None)

axis=0 열을 의미 , axis=1 행을 의미한다. 

In [96]:
df.count()

state    5
year     5
pop      5
dtype: int64

loc와 iloc의 차이 <br>
loc는 필드의 label 이용 즉 인덱싱 값 name을 사용 <br>
iloc는 위치 인덱싱을 사용한다. 즉 이름이 지정되어도 순서로 추출가능

filter() 추출하고자 하는 열을 지정한다 like이용 해당 값이 label로 지정된 열 가져올 수 있다. 

In [100]:
display(df.filter(like='s'))
display(df.filter(['state', 'year']))

state
0    Ohio
1    Ohio
2    Ohio
3  Nevada
4  Nevada

state  year
0    Ohio  2003
1    Ohio  2004
2    Ohio  2005
3  Nevada  2004
4  Nevada  2005

In [101]:
df.select_dtypes(['float'])

pop
0  1.5
1  1.7
2  3.6
3  2.4
4  2.9

boolean indexing 사용할 때 iloc는 불가능 하다. loc만 가능 True인 값만 추출 할 수 있다. 

In [102]:
df.year.isin([2000, 2001]) # df.year에 2000과 2001이 들어가 있는가를 묻는것.

0    False
1    False
2    False
3    False
4    False
Name: year, dtype: bool

query문 이용하면 여러가지 제약조건 집어넣어 한번에 추출할 수 있다. 따옴표 안에 추출하고자 하는 조건 인덱싱을 지정한다. <br>
따로 지정된 변수를 이용하려면 변수 앞에 @를 붙여주어야 한다.

In [105]:
df.query('(pop > 2) & (year > 2004)') 

state  year  pop
2    Ohio  2005  3.6
4  Nevada  2005  2.9

In [106]:
df[(df['pop']>2) & (df['year']>2004)]

state  year  pop
2    Ohio  2005  3.6
4  Nevada  2005  2.9

In [104]:
df.query('pop > pop.mean()').filter(['year', 'pop'])

year  pop
2  2005  3.6
4  2005  2.9

In [108]:
df = df.rename(columns = {'pop': '인구', 'state': '주', 'year':'연도' })
df # feature의 이름 바꾸기. 

주    연도   인구
0    Ohio  2003  1.5
1    Ohio  2004  1.7
2    Ohio  2005  3.6
3  Nevada  2004  2.4
4  Nevada  2005  2.9

In [109]:
df = df.reindex(columns = ['연도', '주', '인구']) # column 이름이 빠지면 안됨.
df

연도       주   인구
0  2003    Ohio  1.5
1  2004    Ohio  1.7
2  2005    Ohio  3.6
3  2004  Nevada  2.4
4  2005  Nevada  2.9

In [110]:
data = DataFrame({'k1': ['one'] * 3 + ['two'] * 4,
                  'k2': [1, 1, 2, 3, 3, 4, 4]})
data.drop_duplicates()

k1  k2
0  one   1
2  one   2
3  two   3
5  two   4

In [114]:
data.drop_duplicates('k1')

k1  k2
0  one   1
3  two   3

In [115]:
data.drop_duplicates(['k1', 'k2'], keep='last')

k1  k2
1  one   1
2  one   2
4  two   3
6  two   4

In [113]:
data.drop('k1',axis=1) # axis=1은 열? 

k2
0   1
1   1
2   2
3   3
4   3
5   4
6   4

In [117]:
data.sample()
# 아무거나 data에 있는 행을 뽑는다. 

k1  k2
4  two   3

In [118]:
data.sample(n=3)

k1  k2
3  two   3
0  one   1
1  one   1

In [119]:
data.sample(frac=0.5)

k1  k2
6  two   4
2  one   2
0  one   1
1  one   1

In [122]:
data.sample(n=3, replace=True)
# replace = True 복원추출! 

k1  k2
6  two   4
6  two   4
4  two   3

In [123]:
data.sample(n=3, random_state=1000)
# random_state 컴퓨터 자체가 랜덤하게 섞는것을 의미한다. 

k1  k2
4  two   3
1  one   1
5  two   4

In [124]:
frame = DataFrame({'b': [4, 7, -3, 2], 'a': [0, 1, 0, 1]})
frame

b  a
0  4  0
1  7  1
2 -3  0
3  2  1

In [125]:
frame.sort_values(by='b')

b  a
2 -3  0
3  2  1
0  4  0
1  7  1

In [126]:
frame.sort_values(by='b', ascending=False)
# 내림차순 정렬. b를 기준으로 정렬. 

b  a
1  7  1
0  4  0
3  2  1
2 -3  0

In [127]:
frame.sort_values(by=['a', 'b'])
# 먼저 쓰인값 정렬 그후 뒤의값 기준 정렬  a 값 기준 정렬 그후 b 값 기준 정렬 

b  a
2 -3  0
0  4  0
3  2  1
1  7  1

In [128]:
frame.rank()

b    a
0  3.0  1.5
1  4.0  3.5
2  1.0  1.5
3  2.0  3.5

In [129]:
frame.rank(method = 'min')

b    a
0  3.0  1.0
1  4.0  3.0
2  1.0  1.0
3  2.0  3.0

In [130]:
df1 = DataFrame({'key': ['b', 'b', 'a', 'c', 'a', 'a', 'b'],
                 'data1': range(7)})
df2 = DataFrame({'key': ['a', 'b', 'd'], 'data2': range(3)})
display(df1)
display(df2)

key  data1
0   b      0
1   b      1
2   a      2
3   c      3
4   a      4
5   a      5
6   b      6

key  data2
0   a      0
1   b      1
2   d      2

In [131]:
pd.merge(df1, df2)
# 알아서 키값을 찾아서 하는데 추천하는 방식은 아님. default default값 inner 조인 

key  data1  data2
0   b      0      1
1   b      1      1
2   b      6      1
3   a      2      0
4   a      4      0
5   a      5      0

In [137]:
pd.merge(df1, df2,how='inner') # outer, inner, left,right

key  data1  data2
0   b      0      1
1   b      1      1
2   b      6      1
3   a      2      0
4   a      4      0
5   a      5      0

In [132]:
pd.merge(df1, df2, on='key')

key  data1  data2
0   b      0      1
1   b      1      1
2   b      6      1
3   a      2      0
4   a      4      0
5   a      5      0

In [138]:
df3 = DataFrame({'lkey': ['b', 'b', 'a', 'c', 'a', 'a', 'b'],
                 'data1': range(7)})
df4 = DataFrame({'rkey': ['a', 'b', 'd'], 'data2': range(3)})
pd.merge(df3, df4, left_on='lkey', right_on='rkey')
# left_on right_on 으로 왼쪽 df 의 키 오른쪽 df의 키값 지정 하지만 이렇게 하면 키값이 남아있기 때문에 중복되는 열이 있음. 

lkey  data1 rkey  data2
0    b      0    b      1
1    b      1    b      1
2    b      6    b      1
3    a      2    a      0
4    a      4    a      0
5    a      5    a      0

In [141]:
df5 = DataFrame({'key': ['a', 'b', 'd'], 'data1': range(3)})
pd.concat([df1, df5])

key  data1
0   b      0
1   b      1
2   a      2
3   c      3
4   a      4
5   a      5
6   b      6
0   a      0
1   b      1
2   d      2

In [142]:
pd.concat([df1, df5], axis=1)
# 해당 위치에 그냥 바로 붙여버린다.  
# 나머지 값에는 NaN이 들어간다. 

key  data1  key  data1
0   b      0    a    0.0
1   b      1    b    1.0
2   a      2    d    2.0
3   c      3  NaN    NaN
4   a      4  NaN    NaN
5   a      5  NaN    NaN
6   b      6  NaN    NaN

In [146]:
df = DataFrame({'key1' : ['a', 'a', 'b', 'b', 'a'],
                'key2' : ['one', 'two', 'one', 'two', 'one'],
                'data1' : np.random.randn(5),
                'data2' : np.random.randn(5)})
display(df.groupby('key1')['data1'].agg([('평균','mean'), ('표준편차','std')]).reset_index())
# 적용 함수의 이름을 지정할 수 있다. 
display(df.groupby('key1').agg({'data1' : 'mean', 'data2' : 'std'}).reset_index())

key1        평균      표준편차
0    a -0.620230  1.164436
1    b  0.079869  1.222514

key1     data1     data2
0    a -0.620230  0.461078
1    b  0.079869  0.602628

In [147]:
tr = pd.DataFrame({
        'id': [1,1,1,1,2,2,2],
        'site': ['a','b','c','a','a','b','b'],
        'pageview': np.arange(1,8),
        'dwelltime': np.arange(7.0, 0, -1),
    }, columns=['id','site','pageview','dwelltime'])
tr

id site  pageview  dwelltime
0   1    a         1        7.0
1   1    b         2        6.0
2   1    c         3        5.0
3   1    a         4        4.0
4   2    a         5        3.0
5   2    b         6        2.0
6   2    b         7        1.0

In [148]:
pv = pd.pivot_table(tr, values='pageview', index='id', columns='site',
                    aggfunc=sum, fill_value=0).reset_index()
pv.columns.name = None; pv # pv.index.name = None  index위치 바꾸려면 loc .loc 이용 원하는 위치에 원하는 index 지정해주면 된다. 
# site를 지워버림. 

id  a   b  c
0   1  5   2  3
1   2  5  13  0

In [3]:
print(Series(range(1,5)).apply(lambda x,y: x+y, args=(3,)))
print(Series(range(1,5)).apply(lambda x,y,z: x+y+z, args=(3,5)))

0    4
1    5
2    6
3    7
dtype: int64
0     9
1    10
2    11
3    12
dtype: int64


In [6]:
tr = pd.DataFrame({
        'id': [1,1,1,1,2,2,2],
        'site': ['a','b','c','a','a','b','b'],
        'pageview': np.arange(1,8),
        'dwelltime': np.arange(7.0, 0, -1),
    }, columns=['id','site','pageview','dwelltime'])
print(tr)
np.random.seed(123)
frame = DataFrame(np.random.randn(4,3), columns=list('abc'))
print(frame)

   id site  pageview  dwelltime
0   1    a         1        7.0
1   1    b         2        6.0
2   1    c         3        5.0
3   1    a         4        4.0
4   2    a         5        3.0
5   2    b         6        2.0
6   2    b         7        1.0
          a         b         c
0 -1.085631  0.997345  0.282978
1 -1.506295 -0.578600  1.651437
2 -2.426679 -0.428913  1.265936
3 -0.866740 -0.678886 -0.094709


In [5]:
def normalize(x, min, max): 
    return (x-min)/(max-min)

min = tr['pageview'].min(); max = tr['pageview'].max();
tr['pageview'].apply(normalize, args=(min, max)) # normalize의 인자가 3개 필요하기 때문에 args 이용 변수 지정.

0    0.000000
1    0.166667
2    0.333333
3    0.500000
4    0.666667
5    0.833333
6    1.000000
Name: pageview, dtype: float64

In [7]:
f = lambda x: x.max() - x.min()
frame.apply(f, axis=1)

0    2.082976
1    3.157731
2    3.692616
3    0.772031
dtype: float64

In [11]:
frame['target'] = ['Y','N','Y','N']
frame

a         b         c target
0 -1.085631  0.997345  0.282978      Y
1 -1.506295 -0.578600  1.651437      N
2 -2.426679 -0.428913  1.265936      Y
3 -0.866740 -0.678886 -0.094709      N

In [12]:
frame.target = frame.target.map({'Y':1, 'N':0})
frame

a         b         c  target
0 -1.085631  0.997345  0.282978       1
1 -1.506295 -0.578600  1.651437       0
2 -2.426679 -0.428913  1.265936       1
3 -0.866740 -0.678886 -0.094709       0

In [16]:
t = Series(pd.date_range('2018-04-16', periods=5));t

0   2018-04-16
1   2018-04-17
2   2018-04-18
3   2018-04-19
4   2018-04-20
dtype: datetime64[ns]

In [17]:
s = Series(['2018-04-16', '2018-04-17', '2018-04-18', '2018-04-19', '2018-04-20']);s

0    2018-04-16
1    2018-04-17
2    2018-04-18
3    2018-04-19
4    2018-04-20
dtype: object

In [18]:
t1 = pd.to_datetime(s);t1 # pd.to_datrtime(바꾸고자 하는 feature, format='%Y%m%d') 포멧은 저장되어있는 값에따라 변한다. 

0   2018-04-16
1   2018-04-17
2   2018-04-18
3   2018-04-19
4   2018-04-20
dtype: datetime64[ns]

In [23]:
t.dt.year , t.dt.month, t.dt.day, t.dt.weekday, t.dt.dayofweek,t.dt.dayofyear

(0    2018
 1    2018
 2    2018
 3    2018
 4    2018
 dtype: int64, 0    4
 1    4
 2    4
 3    4
 4    4
 dtype: int64, 0    16
 1    17
 2    18
 3    19
 4    20
 dtype: int64, 0    0
 1    1
 2    2
 3    3
 4    4
 dtype: int64, 0    0
 1    1
 2    2
 3    3
 4    4
 dtype: int64, 0    106
 1    107
 2    108
 3    109
 4    110
 dtype: int64)

In [24]:
list(zip(t.dt.year, t.dt.month, t.dt.day, t.dt.dayofweek))

[(2018, 4, 16, 0),
 (2018, 4, 17, 1),
 (2018, 4, 18, 2),
 (2018, 4, 19, 3),
 (2018, 4, 20, 4)]

In [30]:
list(zip(t.apply(lambda x: x.weekday()), t.dt.weekday_name))

[(0, 'Monday'),
 (1, 'Tuesday'),
 (2, 'Wednesday'),
 (3, 'Thursday'),
 (4, 'Friday')]

In [31]:
# 2018-01-01부터의 경과일 계산
edays = t - pd.to_datetime('2018-01-01') # 특정 날짜로부터 몇일 지났는지 계산 가능. 
edays
# edays.astyoe('timedelta[D]') 하면 D = 날짜 , M = 월단위, Y = 연단위로 알 수 있다. 일자만 뽑으려면 astype('timedelta[D]').astype('int') 해주어야함. 

0   105 days
1   106 days
2   107 days
3   108 days
4   109 days
dtype: timedelta64[ns]

In [32]:
df3 = DataFrame({'lkey': ['b', 'b', 'a', 'c', 'a', 'a', 'b'],
                 'data1': range(7)})
df4 = DataFrame({'rkey': ['a', 'b', 'd'], 'data2': range(3)})
df5 = pd.merge(df3,df4,left_on='lkey',right_on='rkey',how='outer')
df5

lkey  data1 rkey  data2
0    b    0.0    b    1.0
1    b    1.0    b    1.0
2    b    6.0    b    1.0
3    a    2.0    a    0.0
4    a    4.0    a    0.0
5    a    5.0    a    0.0
6    c    3.0  NaN    NaN
7  NaN    NaN    d    2.0

In [33]:
pd.isnull(df5) # df5에 NaN 값이 어디어디 들어가있는지 판별. 

lkey  data1   rkey  data2
0  False  False  False  False
1  False  False  False  False
2  False  False  False  False
3  False  False  False  False
4  False  False  False  False
5  False  False  False  False
6  False  False   True   True
7   True   True  False  False

In [34]:
pd.notnull(df5.data1) # notnull NaN값이 아닌지에 대한 판별

0     True
1     True
2     True
3     True
4     True
5     True
6     True
7    False
Name: data1, dtype: bool

In [35]:
df5.dropna(how='any') # how 인자에 all을 넣으면 모든 행의 값이 NaN이여야 삭제. 
# 해당 행의 값중 NaN 값이 있다면 해당 행 삭제 

lkey  data1 rkey  data2
0    b    0.0    b    1.0
1    b    1.0    b    1.0
2    b    6.0    b    1.0
3    a    2.0    a    0.0
4    a    4.0    a    0.0
5    a    5.0    a    0.0

In [37]:
df5.fillna({'data1': 1.5, 'data2': 0.5, 'lkey': 'Y', 'rkey': ''})
# NaN값 채워 넣을때 feature 별로 다른 값 넣을 수 있다. 

lkey  data1 rkey  data2
0    b    0.0    b    1.0
1    b    1.0    b    1.0
2    b    6.0    b    1.0
3    a    2.0    a    0.0
4    a    4.0    a    0.0
5    a    5.0    a    0.0
6    c    3.0         0.5
7    Y    1.5    d    2.0

In [38]:
profile = pd.DataFrame({'name': list('ABCDEFGH'),
                        'age': [10, 15, 13, 12, 25, 28, 59, 60]})
profile

name  age
0    A   10
1    B   15
2    C   13
3    D   12
4    E   25
5    F   28
6    G   59
7    H   60

In [43]:
profile['age_group'] = pd.cut(profile.age, bins=[0, 20, 30, 70], 
                              right=False, 
                              labels=['10대', '20대', '30대이상'])
# right = False를 지정해 줌으로써 30살이 20대로 들어가는것 막음.ㅇ
profile

name  age age_group
0    A   10       10대
1    B   15       10대
2    C   13       10대
3    D   12       10대
4    E   25       20대
5    F   28       20대
6    G   59     30대이상
7    H   60     30대이상

In [46]:
ctab = pd.crosstab(tr['id'], tr['site'],).reset_index() 
ctab.index.name = None; ctab.columns.name = None
ctab

id  a  b  c
0   1  2  1  1
1   2  1  2  0

In [49]:
np.linspace(1, 2, 9),np.arange(1, 2, 0.1),np.arange(10),np.ones_like(np.linspace(1, 2, 9))

(array([1.   , 1.125, 1.25 , 1.375, 1.5  , 1.625, 1.75 , 1.875, 2.   ]),
 array([1. , 1.1, 1.2, 1.3, 1.4, 1.5, 1.6, 1.7, 1.8, 1.9]),
 array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9]),
 array([1., 1., 1., 1., 1., 1., 1., 1., 1.]))

@ 행렬곱 연산 가능, 행렬.dot(행렬) 행렬곱 가능. 행렬.transpose() 전치행렬, 행렬.T 전치행렬, np.dot(행렬,행렬) 행렬곱

In [52]:
a = np.arange(7,13)
a.reshape(6,1)

array([[ 7],
       [ 8],
       [ 9],
       [10],
       [11],
       [12]])

 reshape(행,열) 열위치에 -1을 두면 행은 해당 숫자만큼 고정 열이 변동 행에-1 두면 열고정 행 알아서 나눔. 

np.vstack((행렬,행렬)) rbind와 비슷 np.hstack((행렬,행렬)) cbind와 비슷

In [53]:
np.random.rand(10)

array([0.39804426, 0.73799541, 0.18249173, 0.17545176, 0.53155137,
       0.53182759, 0.63440096, 0.84943179, 0.72445532, 0.61102351])

np.where(조건,참,거짓) 엑셀에서 if와 같다. if쓰는것보다 간편.

pd.get_dummies(df,columns=[feature]) 해당 열이 가지고 있는 값을 columns로 보내는 방법. 다양한 인자들을 행으로 보낼때 이용한다. 

In [8]:
data = pd.DataFrame(data)
display(data)
display(pd.get_dummies(data,columns=['state']))

state  year  pop
0    Ohio  2000  1.5
1    Ohio  2001  1.7
2    Ohio  2002  3.6
3  Nevada  2001  2.4
4  Nevada  2002  2.9

year  pop  state_Nevada  state_Ohio
0  2000  1.5             0           1
1  2001  1.7             0           1
2  2002  3.6             0           1
3  2001  2.4             1           0
4  2002  2.9             1           0